"""Indian cinema augmentation: a curated catalog + seeded ratings.

MovieLens has no Indian cinema, so we append a hand-curated list of ~420
popular Indian films across Hindi, Tamil, Telugu, Malayalam, Kannada, Marathi,
Bengali and Punjabi. Synthetic "critic" users seed ratings for these titles so
the collaborative paths (popularity + item-based CF) can score them too, while
the semantic path embeds every title so natural-language search finds them.

The augmentation is idempotent: it checks for an existing ``origin == "indian"``
marker column in the cached parquet and returns early if already applied.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

# (title, year, language, genres)
INDIAN_MOVIES: list[tuple[str, int, str, list[str]]] = [
    # ------------------------------------------------------------------ Hindi
    ("Mughal-e-Azam", 1960, "Hindi", ["Drama", "Romance", "Musical", "War"]),
    ("Guide", 1965, "Hindi", ["Drama", "Romance", "Musical"]),
    ("Anand", 1971, "Hindi", ["Drama", "Musical"]),
    ("Sholay", 1975, "Hindi", ["Action", "Adventure", "Comedy", "Drama"]),
    ("Deewaar", 1975, "Hindi", ["Action", "Crime", "Drama"]),
    ("Chupke Chupke", 1975, "Hindi", ["Comedy", "Romance"]),
    ("Amar Akbar Anthony", 1977, "Hindi", ["Comedy", "Drama", "Musical"]),
    ("Don", 1978, "Hindi", ["Action", "Crime", "Thriller"]),
    ("Gol Maal", 1979, "Hindi", ["Comedy"]),
    ("Mr India", 1987, "Hindi", ["Sci-Fi", "Action", "Comedy", "Adventure"]),
    ("Qayamat Se Qayamat Tak", 1988, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Maine Pyar Kiya", 1989, "Hindi", ["Romance", "Musical", "Drama"]),
    ("Dil", 1990, "Hindi", ["Romance", "Drama"]),
    ("Jo Jeeta Wohi Sikandar", 1992, "Hindi", ["Comedy", "Drama", "Sport"]),
    ("Aankhen", 1993, "Hindi", ["Action", "Comedy", "Crime"]),
    ("Hum Aapke Hain Koun", 1994, "Hindi", ["Romance", "Musical", "Drama", "Family"]),
    ("Andaz Apna Apna", 1994, "Hindi", ["Comedy", "Crime"]),
    ("Karan Arjun", 1995, "Hindi", ["Action", "Fantasy", "Drama"]),
    ("Dilwale Dulhania Le Jayenge", 1995, "Hindi", ["Romance", "Drama", "Musical", "Family"]),
    ("Rangeela", 1995, "Hindi", ["Romance", "Musical", "Drama"]),
    ("Dil To Pagal Hai", 1997, "Hindi", ["Romance", "Musical", "Drama"]),
    ("Border", 1997, "Hindi", ["War", "Action", "Drama"]),
    ("Dil Se", 1998, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Satya", 1998, "Hindi", ["Crime", "Drama"]),
    ("Kuch Kuch Hota Hai", 1998, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Zakhm", 1998, "Hindi", ["Drama"]),
    ("Pyaar Kiya To Darna Kya", 1998, "Hindi", ["Romance", "Comedy"]),
    ("Sarfarosh", 1999, "Hindi", ["Action", "Thriller", "Drama"]),
    ("Hum Dil De Chuke Sanam", 1999, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Taal", 1999, "Hindi", ["Romance", "Musical", "Drama"]),
    ("Vaastav", 1999, "Hindi", ["Crime", "Drama"]),
    ("Hera Pheri", 2000, "Hindi", ["Comedy", "Crime"]),
    ("Kaho Naa... Pyaar Hai", 2000, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Mohabbatein", 2000, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Dhadkan", 2000, "Hindi", ["Romance", "Drama"]),
    ("Lagaan", 2001, "Hindi", ["Drama", "Musical", "Sport"]),
    ("Dil Chahta Hai", 2001, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Kabhi Khushi Kabhie Gham", 2001, "Hindi", ["Drama", "Romance", "Musical", "Family"]),
    ("Gadar: Ek Prem Katha", 2001, "Hindi", ["Action", "Drama", "Romance"]),
    ("Monsoon Wedding", 2001, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Company", 2002, "Hindi", ["Crime", "Drama", "Thriller"]),
    ("Kaante", 2002, "Hindi", ["Action", "Crime", "Thriller"]),
    ("Devdas", 2002, "Hindi", ["Drama", "Romance", "Musical"]),
    ("The Legend of Bhagat Singh", 2002, "Hindi", ["Drama", "Biography"]),
    ("Koi... Mil Gaya", 2003, "Hindi", ["Sci-Fi", "Fantasy", "Drama"]),
    ("Munna Bhai M.B.B.S.", 2003, "Hindi", ["Comedy", "Drama"]),
    ("Kal Ho Naa Ho", 2003, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Veer-Zaara", 2004, "Hindi", ["Drama", "Romance"]),
    ("Swades", 2004, "Hindi", ["Drama"]),
    ("Black", 2005, "Hindi", ["Drama"]),
    ("Parineeta", 2005, "Hindi", ["Romance", "Drama", "Musical"]),
    ("Rang De Basanti", 2006, "Hindi", ["Drama", "Comedy"]),
    ("Lage Raho Munna Bhai", 2006, "Hindi", ["Comedy", "Drama"]),
    ("Omkara", 2006, "Hindi", ["Crime", "Drama"]),
    ("Dhoom 2", 2006, "Hindi", ["Action", "Crime", "Thriller"]),
    ("Krrish", 2006, "Hindi", ["Action", "Sci-Fi"]),
    ("Golmaal", 2006, "Hindi", ["Comedy"]),
    ("Chak De! India", 2007, "Hindi", ["Sport", "Drama"]),
    ("Taare Zameen Par", 2007, "Hindi", ["Drama", "Family"]),
    ("Om Shanti Om", 2007, "Hindi", ["Drama", "Romance", "Musical"]),
    ("Guru", 2007, "Hindi", ["Drama", "Biography"]),
    ("Welcome", 2007, "Hindi", ["Comedy", "Crime"]),
    ("Bhool Bhulaiyaa", 2007, "Hindi", ["Comedy", "Horror", "Thriller"]),
    ("Jodhaa Akbar", 2008, "Hindi", ["Drama", "Romance", "War"]),
    ("Ghajini", 2008, "Hindi", ["Action", "Thriller"]),
    ("A Wednesday", 2008, "Hindi", ["Thriller", "Crime", "Drama"]),
    ("Rock On!!", 2008, "Hindi", ["Drama", "Musical"]),
    ("Jaane Tu... Ya Jaane Na", 2008, "Hindi", ["Comedy", "Romance", "Drama"]),
    ("Rab Ne Bana Di Jodi", 2008, "Hindi", ["Romance", "Comedy", "Drama"]),
    ("Golmaal Returns", 2008, "Hindi", ["Comedy"]),
    ("Dev D", 2009, "Hindi", ["Drama", "Romance"]),
    ("Kaminey", 2009, "Hindi", ["Crime", "Drama", "Thriller"]),
    ("3 Idiots", 2009, "Hindi", ["Comedy", "Drama"]),
    ("Wake Up Sid", 2009, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Rocket Singh: Salesman of the Year", 2009, "Hindi", ["Comedy", "Drama"]),
    ("Love Aaj Kal", 2009, "Hindi", ["Romance", "Drama"]),
    ("Dabangg", 2010, "Hindi", ["Action", "Comedy", "Drama"]),
    ("Peepli Live", 2010, "Hindi", ["Comedy", "Drama"]),
    ("Once Upon a Time in Mumbaai", 2010, "Hindi", ["Crime", "Drama"]),
    ("Band Baaja Baaraat", 2010, "Hindi", ["Comedy", "Romance", "Drama"]),
    ("Tanu Weds Manu", 2011, "Hindi", ["Comedy", "Romance"]),
    ("Zindagi Na Milegi Dobara", 2011, "Hindi", ["Comedy", "Drama", "Adventure"]),
    ("Rockstar", 2011, "Hindi", ["Drama", "Musical", "Romance"]),
    ("Delhi Belly", 2011, "Hindi", ["Comedy", "Crime"]),
    ("The Dirty Picture", 2011, "Hindi", ["Comedy", "Drama", "Biography"]),
    ("Gangs of Wasseypur", 2012, "Hindi", ["Crime", "Drama"]),
    ("Barfi!", 2012, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Vicky Donor", 2012, "Hindi", ["Comedy", "Romance"]),
    ("Paan Singh Tomar", 2012, "Hindi", ["Drama", "Biography"]),
    ("Special 26", 2013, "Hindi", ["Crime", "Thriller"]),
    ("Jolly LLB", 2013, "Hindi", ["Comedy", "Drama"]),
    ("Raanjhanaa", 2013, "Hindi", ["Romance", "Drama"]),
    ("Bhaag Milkha Bhaag", 2013, "Hindi", ["Drama", "Biography", "Sport"]),
    ("Queen", 2013, "Hindi", ["Comedy", "Drama"]),
    ("Chennai Express", 2013, "Hindi", ["Action", "Comedy", "Romance"]),
    ("Lootera", 2013, "Hindi", ["Romance", "Drama"]),
    ("Aashiqui 2", 2013, "Hindi", ["Romance", "Musical", "Drama"]),
    ("Highway", 2014, "Hindi", ["Drama"]),
    ("2 States", 2014, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("PK", 2014, "Hindi", ["Comedy", "Sci-Fi", "Drama"]),
    ("Mary Kom", 2014, "Hindi", ["Drama", "Sport", "Biography"]),
    ("Mardani", 2014, "Hindi", ["Crime", "Thriller", "Drama"]),
    ("Bajrangi Bhaijaan", 2015, "Hindi", ["Action", "Comedy", "Drama"]),
    ("Dil Dhadakne Do", 2015, "Hindi", ["Comedy", "Drama", "Adventure"]),
    ("Tanu Weds Manu Returns", 2015, "Hindi", ["Comedy", "Drama"]),
    ("Baby", 2015, "Hindi", ["Action", "Thriller"]),
    ("Piku", 2015, "Hindi", ["Comedy", "Drama"]),
    ("Bajirao Mastani", 2015, "Hindi", ["Drama", "War", "Romance"]),
    ("Neerja", 2016, "Hindi", ["Drama", "Biography", "Thriller"]),
    ("Kapoor & Sons", 2016, "Hindi", ["Comedy", "Drama", "Family"]),
    ("Airlift", 2016, "Hindi", ["Drama", "Thriller"]),
    ("Dangal", 2016, "Hindi", ["Drama", "Sport", "Family"]),
    ("Pink", 2016, "Hindi", ["Drama", "Thriller"]),
    ("Dear Zindagi", 2016, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Rustom", 2016, "Hindi", ["Drama", "Thriller"]),
    ("M.S. Dhoni: The Untold Story", 2016, "Hindi", ["Drama", "Biography", "Sport"]),
    ("Ae Dil Hai Mushkil", 2016, "Hindi", ["Drama", "Romance", "Musical"]),
    ("Hindi Medium", 2017, "Hindi", ["Comedy", "Drama"]),
    ("Badrinath Ki Dulhania", 2017, "Hindi", ["Comedy", "Romance"]),
    ("Jolly LLB 2", 2017, "Hindi", ["Comedy", "Drama"]),
    ("Newton", 2017, "Hindi", ["Comedy", "Drama"]),
    ("The Ghazi Attack", 2017, "Hindi", ["War", "Thriller"]),
    ("Raees", 2017, "Hindi", ["Action", "Crime", "Drama"]),
    ("Padmaavat", 2018, "Hindi", ["Drama", "War"]),
    ("Raazi", 2018, "Hindi", ["Drama", "Thriller"]),
    ("Stree", 2018, "Hindi", ["Comedy", "Horror"]),
    ("Andhadhun", 2018, "Hindi", ["Thriller", "Comedy", "Crime"]),
    ("Badhaai Ho", 2018, "Hindi", ["Comedy", "Drama"]),
    ("Sonu Ke Titu Ki Sweety", 2018, "Hindi", ["Comedy", "Romance"]),
    ("Pad Man", 2018, "Hindi", ["Comedy", "Drama"]),
    ("Article 15", 2019, "Hindi", ["Crime", "Drama", "Thriller"]),
    ("Gully Boy", 2019, "Hindi", ["Drama", "Musical"]),
    ("Uri: The Surgical Strike", 2019, "Hindi", ["Action", "War", "Drama"]),
    ("Super 30", 2019, "Hindi", ["Drama", "Biography"]),
    ("Kabir Singh", 2019, "Hindi", ["Drama", "Romance"]),
    ("Chhichhore", 2019, "Hindi", ["Comedy", "Drama"]),
    ("Good Newwz", 2019, "Hindi", ["Comedy", "Drama"]),
    ("Bala", 2019, "Hindi", ["Comedy", "Drama"]),
    ("Dream Girl", 2019, "Hindi", ["Comedy", "Drama"]),
    ("War", 2019, "Hindi", ["Action", "Thriller"]),
    ("Mission Mangal", 2019, "Hindi", ["Drama", "Adventure"]),
    ("Mardaani 2", 2019, "Hindi", ["Crime", "Thriller"]),
    ("Tanhaji: The Unsung Warrior", 2020, "Hindi", ["Action", "War", "Drama"]),
    ("Dil Bechara", 2020, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Shershaah", 2021, "Hindi", ["War", "Drama", "Action"]),
    ("83", 2021, "Hindi", ["Drama", "Sport", "Biography"]),
    ("Sooryavanshi", 2021, "Hindi", ["Action", "Crime", "Thriller"]),
    ("Gangubai Kathiawadi", 2022, "Hindi", ["Drama", "Crime", "Biography"]),
    ("The Kashmir Files", 2022, "Hindi", ["Drama"]),
    ("Bhool Bhulaiyaa 2", 2022, "Hindi", ["Comedy", "Horror"]),
    ("Laal Singh Chaddha", 2022, "Hindi", ["Comedy", "Drama"]),
    ("Darlings", 2022, "Hindi", ["Comedy", "Drama"]),
    ("Qala", 2022, "Hindi", ["Drama"]),
    ("Pathaan", 2023, "Hindi", ["Action", "Thriller"]),
    ("Jawan", 2023, "Hindi", ["Action", "Thriller", "Drama"]),
    ("Animal", 2023, "Hindi", ["Crime", "Drama", "Action"]),
    ("12th Fail", 2023, "Hindi", ["Drama", "Biography"]),
    ("Rocky Aur Rani Kii Prem Kahaani", 2023, "Hindi", ["Comedy", "Drama", "Romance"]),
    ("Dunki", 2023, "Hindi", ["Comedy", "Drama"]),
    ("Fighter", 2024, "Hindi", ["Action", "Drama"]),
    # ------------------------------------------------------------------ Tamil
    ("Nayakan", 1987, "Tamil", ["Crime", "Drama"]),
    ("Michael Madana Kama Rajan", 1990, "Tamil", ["Comedy"]),
    ("Anjali", 1990, "Tamil", ["Drama"]),
    ("Thalapathi", 1991, "Tamil", ["Drama", "Action"]),
    ("Guna", 1991, "Tamil", ["Drama", "Thriller"]),
    ("Roja", 1992, "Tamil", ["Drama", "Romance", "Thriller"]),
    ("Gentleman", 1993, "Tamil", ["Action", "Thriller"]),
    ("Kadhalan", 1994, "Tamil", ["Romance", "Action", "Musical"]),
    ("Bombay", 1995, "Tamil", ["Drama", "Romance"]),
    ("Kuruthipunal", 1995, "Tamil", ["Action", "Thriller"]),
    ("Indian", 1996, "Tamil", ["Action", "Thriller", "Drama"]),
    ("Minsara Kanavu", 1997, "Tamil", ["Romance", "Musical"]),
    ("Jeans", 1998, "Tamil", ["Romance", "Comedy", "Drama"]),
    ("Padaiyappa", 1999, "Tamil", ["Drama", "Action"]),
    ("Mudhalvan", 1999, "Tamil", ["Drama", "Thriller"]),
    ("Hey Ram", 2000, "Tamil", ["Drama"]),
    ("Alaipayuthey", 2000, "Tamil", ["Romance", "Drama"]),
    ("Kandukondain Kandukondain", 2000, "Tamil", ["Romance", "Drama"]),
    ("Ghilli", 2004, "Tamil", ["Action", "Comedy", "Drama"]),
    ("Virumaandi", 2004, "Tamil", ["Crime", "Drama"]),
    ("Anniyan", 2005, "Tamil", ["Action", "Thriller", "Drama"]),
    ("Vettaiyaadu Vilaiyaadu", 2006, "Tamil", ["Crime", "Thriller"]),
    ("Chennai 600028", 2007, "Tamil", ["Comedy", "Sport"]),
    ("Paruthiveeran", 2007, "Tamil", ["Drama", "Romance"]),
    ("Sivaji", 2007, "Tamil", ["Action", "Drama"]),
    ("Polladhavan", 2007, "Tamil", ["Action", "Drama"]),
    ("Subramaniapuram", 2008, "Tamil", ["Crime", "Drama"]),
    ("Vaaranam Aayiram", 2008, "Tamil", ["Romance", "Drama"]),
    ("Dasavathaaram", 2008, "Tamil", ["Action", "Drama", "Sci-Fi"]),
    ("Yaaradi Nee Mohini", 2008, "Tamil", ["Romance", "Drama"]),
    ("Enthiran", 2010, "Tamil", ["Sci-Fi", "Action"]),
    ("Aadukalam", 2011, "Tamil", ["Drama"]),
    ("Ko", 2011, "Tamil", ["Thriller", "Drama"]),
    ("3", 2012, "Tamil", ["Romance", "Thriller", "Drama"]),
    ("Thuppakki", 2012, "Tamil", ["Action", "Thriller"]),
    ("Naduvula Konjam Pakkatha Kaanom", 2012, "Tamil", ["Comedy"]),
    ("Soodhu Kavvum", 2013, "Tamil", ["Comedy", "Crime"]),
    ("Raja Rani", 2013, "Tamil", ["Romance", "Drama"]),
    ("Kaththi", 2014, "Tamil", ["Action", "Drama"]),
    ("Jigarthanda", 2014, "Tamil", ["Comedy", "Crime"]),
    ("Madras", 2014, "Tamil", ["Drama"]),
    ("Visaranai", 2015, "Tamil", ["Crime", "Drama"]),
    ("Theri", 2016, "Tamil", ["Action"]),
    ("Kabali", 2016, "Tamil", ["Action", "Drama"]),
    ("Mersal", 2017, "Tamil", ["Action", "Drama"]),
    ("Vikram Vedha", 2017, "Tamil", ["Crime", "Thriller"]),
    ("96", 2018, "Tamil", ["Romance", "Drama"]),
    ("Ratsasan", 2018, "Tamil", ["Crime", "Thriller"]),
    ("Super Deluxe", 2019, "Tamil", ["Drama", "Thriller"]),
    ("Pariyerum Perumal", 2018, "Tamil", ["Drama"]),
    ("Vada Chennai", 2018, "Tamil", ["Crime", "Drama"]),
    ("Asuran", 2019, "Tamil", ["Action", "Drama"]),
    ("Kaithi", 2019, "Tamil", ["Action", "Thriller"]),
    ("Petta", 2019, "Tamil", ["Action", "Drama"]),
    ("2.0", 2018, "Tamil", ["Sci-Fi", "Action"]),
    ("Soorarai Pottru", 2020, "Tamil", ["Drama", "Biography"]),
    ("Mandela", 2021, "Tamil", ["Comedy", "Drama"]),
    ("Master", 2021, "Tamil", ["Action", "Thriller", "Drama"]),
    ("Jai Bhim", 2021, "Tamil", ["Crime", "Drama"]),
    ("Karnan", 2021, "Tamil", ["Drama", "Action"]),
    ("Ponniyin Selvan: I", 2022, "Tamil", ["Drama", "Adventure"]),
    ("Ponniyin Selvan: II", 2023, "Tamil", ["Drama", "Adventure"]),
    ("Vikram", 2022, "Tamil", ["Action", "Thriller"]),
    ("Sardar", 2022, "Tamil", ["Action", "Thriller"]),
    ("Leo", 2023, "Tamil", ["Action", "Crime", "Thriller"]),
    ("Jailer", 2023, "Tamil", ["Action", "Comedy", "Drama"]),
    ("Jigarthanda Double X", 2023, "Tamil", ["Action", "Comedy"]),
    ("Good Night", 2023, "Tamil", ["Romance", "Comedy", "Drama"]),
    ("Meiyazhagan", 2024, "Tamil", ["Drama", "Romance"]),
    # ------------------------------------------------------------------ Telugu
    ("Devadasu", 1953, "Telugu", ["Drama", "Romance"]),
    ("Missamma", 1955, "Telugu", ["Comedy", "Drama"]),
    ("Mayabazar", 1957, "Telugu", ["Fantasy", "Drama", "Family"]),
    ("Gundamma Katha", 1962, "Telugu", ["Comedy", "Drama"]),
    ("Jagadeka Veerudu Athiloka Sundari", 1990, "Telugu", ["Fantasy", "Romance", "Adventure"]),
    ("Simhadri", 2003, "Telugu", ["Action", "Drama"]),
    ("Magadheera", 2009, "Telugu", ["Action", "Fantasy"]),
    ("Khaleja", 2010, "Telugu", ["Action", "Comedy", "Fantasy"]),
    ("Dookudu", 2011, "Telugu", ["Action", "Comedy"]),
    ("Ala Modalaindi", 2011, "Telugu", ["Romance", "Comedy"]),
    ("Gabbar Singh", 2012, "Telugu", ["Action", "Comedy"]),
    ("Attarintiki Daredi", 2013, "Telugu", ["Comedy", "Drama", "Family"]),
    ("Eega", 2012, "Telugu", ["Fantasy", "Action", "Thriller"]),
    ("Yevade Subramanyam", 2015, "Telugu", ["Drama", "Adventure"]),
    ("Srimanthudu", 2015, "Telugu", ["Action", "Drama"]),
    ("Temper", 2015, "Telugu", ["Action", "Drama"]),
    ("Pataas", 2015, "Telugu", ["Action", "Comedy"]),
    ("Kshanam", 2016, "Telugu", ["Thriller", "Mystery"]),
    ("Janatha Garage", 2016, "Telugu", ["Action", "Drama"]),
    ("Nannaku Prematho", 2016, "Telugu", ["Action", "Drama"]),
    ("Fidaa", 2017, "Telugu", ["Romance"]),
    ("Arjun Reddy", 2017, "Telugu", ["Romance", "Drama"]),
    ("Ghazi", 2017, "Telugu", ["War", "Thriller"]),
    ("Rangasthalam", 2018, "Telugu", ["Drama"]),
    ("Mahanati", 2018, "Telugu", ["Drama", "Biography"]),
    ("Geetha Govindam", 2018, "Telugu", ["Romance", "Comedy"]),
    ("Awe", 2018, "Telugu", ["Drama", "Thriller", "Fantasy"]),
    ("Jersey", 2019, "Telugu", ["Drama", "Sport"]),
    ("Oh! Baby", 2019, "Telugu", ["Comedy", "Fantasy"]),
    ("Dear Comrade", 2019, "Telugu", ["Romance", "Drama"]),
    ("Maharshi", 2019, "Telugu", ["Drama"]),
    ("Baahubali: The Beginning", 2015, "Telugu", ["Action", "Adventure", "Fantasy"]),
    ("Baahubali 2: The Conclusion", 2017, "Telugu", ["Action", "Drama", "Fantasy"]),
    ("Ala Vaikunthapurramuloo", 2020, "Telugu", ["Action", "Comedy", "Drama"]),
    ("Sarileru Neekevvaru", 2020, "Telugu", ["Action", "Comedy"]),
    ("Vakeel Saab", 2021, "Telugu", ["Drama"]),
    ("Pushpa: The Rise", 2021, "Telugu", ["Action", "Crime", "Drama"]),
    ("Sita Ramam", 2022, "Telugu", ["Romance", "Drama", "War"]),
    ("Bheemla Nayak", 2022, "Telugu", ["Action", "Drama"]),
    ("RRR", 2022, "Telugu", ["Action", "Drama"]),
    ("Dasara", 2023, "Telugu", ["Action", "Drama"]),
    ("Balagam", 2023, "Telugu", ["Drama"]),
    ("Virupaksha", 2023, "Telugu", ["Horror", "Thriller"]),
    ("Kushi", 2023, "Telugu", ["Romance", "Comedy", "Drama"]),
    ("Hi Nanna", 2023, "Telugu", ["Romance", "Drama"]),
    ("Guntur Kaaram", 2024, "Telugu", ["Action", "Drama"]),
    ("Devara: Part 1", 2024, "Telugu", ["Action", "Drama"]),
    ("Kalki 2898 AD", 2024, "Telugu", ["Sci-Fi", "Action", "Drama"]),
    ("Amaran", 2024, "Telugu", ["War", "Drama", "Action"]),
    # --------------------------------------------------------------- Malayalam
    ("Chemmeen", 1965, "Malayalam", ["Drama", "Romance"]),
    ("Kireedam", 1989, "Malayalam", ["Drama"]),
    ("Thazhvaram", 1990, "Malayalam", ["Drama"]),
    ("Kilukkam", 1991, "Malayalam", ["Comedy", "Thriller"]),
    ("Manichitrathazhu", 1993, "Malayalam", ["Horror", "Comedy", "Thriller"]),
    ("Spadikam", 1995, "Malayalam", ["Drama", "Action"]),
    ("Vanaprastham", 1999, "Malayalam", ["Drama"]),
    ("Meghamalhar", 2001, "Malayalam", ["Drama", "Romance"]),
    ("Classmates", 2006, "Malayalam", ["Drama", "Thriller"]),
    ("Traffic", 2011, "Malayalam", ["Thriller", "Drama"]),
    ("Salt N Pepper", 2011, "Malayalam", ["Comedy"]),
    ("22 Female Kottayam", 2012, "Malayalam", ["Thriller", "Drama"]),
    ("Ustad Hotel", 2012, "Malayalam", ["Comedy", "Drama"]),
    ("Neram", 2013, "Malayalam", ["Comedy", "Crime", "Thriller"]),
    ("Drishyam", 2013, "Malayalam", ["Thriller", "Drama"]),
    ("Bangalore Days", 2014, "Malayalam", ["Comedy", "Drama", "Romance"]),
    ("Premam", 2015, "Malayalam", ["Romance", "Comedy", "Drama"]),
    ("Charlie", 2015, "Malayalam", ["Drama", "Comedy"]),
    ("Anarkali", 2015, "Malayalam", ["Comedy", "Drama"]),
    ("Angamaly Diaries", 2017, "Malayalam", ["Crime", "Action"]),
    ("Take Off", 2017, "Malayalam", ["Drama", "Thriller"]),
    ("Thondimuthalum Driksakshiyum", 2017, "Malayalam", ["Comedy", "Crime", "Drama"]),
    ("Sudani from Nigeria", 2018, "Malayalam", ["Comedy", "Drama", "Sport"]),
    ("Joseph", 2018, "Malayalam", ["Drama", "Thriller"]),
    ("Kumbalangi Nights", 2019, "Malayalam", ["Drama", "Comedy"]),
    ("Virus", 2019, "Malayalam", ["Drama", "Thriller"]),
    ("Lucifer", 2019, "Malayalam", ["Action", "Crime"]),
    ("Anjaam Pathiraa", 2020, "Malayalam", ["Thriller"]),
    ("The Great Indian Kitchen", 2021, "Malayalam", ["Drama"]),
    ("Joji", 2021, "Malayalam", ["Drama", "Thriller"]),
    ("Nayattu", 2021, "Malayalam", ["Thriller", "Drama"]),
    ("Minnal Murali", 2021, "Malayalam", ["Comedy", "Fantasy", "Action"]),
    ("Malik", 2021, "Malayalam", ["Drama", "Crime"]),
    ("Kuruthi", 2021, "Malayalam", ["Thriller", "Drama"]),
    ("Hridayam", 2022, "Malayalam", ["Romance", "Drama"]),
    ("Bheeshma Parvam", 2022, "Malayalam", ["Drama", "Crime"]),
    ("Rorschach", 2022, "Malayalam", ["Thriller", "Drama"]),
    ("Malayankunju", 2022, "Malayalam", ["Drama"]),
    ("Nanpakal Nerathu Mayakkam", 2023, "Malayalam", ["Drama"]),
    ("2018: Everyone is a Hero", 2023, "Malayalam", ["Drama"]),
    ("RDX", 2023, "Malayalam", ["Action"]),
    ("Aavesham", 2024, "Malayalam", ["Comedy", "Action"]),
    ("Manjummel Boys", 2024, "Malayalam", ["Drama", "Thriller", "Adventure"]),
    ("Bramayugam", 2024, "Malayalam", ["Horror", "Thriller"]),
    ("Premalu", 2024, "Malayalam", ["Comedy", "Romance"]),
    # ---------------------------------------------------------------- Kannada
    ("Pushpaka Vimana", 1987, "Kannada", ["Comedy", "Mystery", "Musical"]),
    ("America America", 1995, "Kannada", ["Comedy", "Drama"]),
    ("Amrutha Varshini", 1997, "Kannada", ["Romance", "Drama"]),
    ("Mungaru Male", 2006, "Kannada", ["Romance", "Drama"]),
    ("Duniya", 2007, "Kannada", ["Drama"]),
    ("Mussanjemaatu", 2008, "Kannada", ["Drama"]),
    ("Gaalipata", 2008, "Kannada", ["Romance", "Comedy", "Drama"]),
    ("Ulidavaru Kandanthe", 2014, "Kannada", ["Drama", "Crime"]),
    ("RangiTaranga", 2015, "Kannada", ["Mystery", "Thriller"]),
    ("Godhi Banna Sadharana Mykattu", 2016, "Kannada", ["Drama"]),
    ("Kirik Party", 2016, "Kannada", ["Comedy", "Drama", "Romance"]),
    ("KGF: Chapter 1", 2018, "Kannada", ["Action", "Crime"]),
    ("KGF: Chapter 2", 2022, "Kannada", ["Action", "Drama"]),
    ("Garuda Gamana Vrishabha Vahana", 2021, "Kannada", ["Crime", "Drama"]),
    ("Kantara", 2022, "Kannada", ["Action", "Drama", "Fantasy"]),
    ("777 Charlie", 2022, "Kannada", ["Comedy", "Drama", "Adventure"]),
    ("Aachar & Co", 2023, "Kannada", ["Comedy", "Drama"]),
    ("Kabzaa", 2023, "Kannada", ["Action"]),
    ("Kaatera", 2023, "Kannada", ["Drama"]),
    # ----------------------------------------------------------------- Marathi
    ("Shwaas", 2004, "Marathi", ["Drama"]),
    ("Harishchandrachi Factory", 2009, "Marathi", ["Comedy", "Drama", "Biography"]),
    ("Deool", 2011, "Marathi", ["Drama", "Comedy"]),
    ("Fandry", 2013, "Marathi", ["Drama"]),
    ("Court", 2014, "Marathi", ["Drama"]),
    ("Killa", 2014, "Marathi", ["Drama"]),
    ("Timepass", 2014, "Marathi", ["Comedy", "Romance"]),
    ("Sairat", 2016, "Marathi", ["Romance", "Drama"]),
    ("Ventilator", 2016, "Marathi", ["Comedy", "Drama"]),
    ("Natsamrat", 2016, "Marathi", ["Drama"]),
    ("Faster Fene", 2017, "Marathi", ["Comedy", "Drama"]),
    ("Naal", 2018, "Marathi", ["Drama"]),
    ("Ani Dr. Kashinath Ghanekar", 2018, "Marathi", ["Drama", "Biography"]),
    ("Pawankhind", 2022, "Marathi", ["War", "Drama"]),
    ("Ved", 2022, "Marathi", ["Drama", "Romance"]),
    # ---------------------------------------------------------------- Bengali
    ("Pather Panchali", 1955, "Bengali", ["Drama"]),
    ("Aparajito", 1956, "Bengali", ["Drama"]),
    ("Apur Sansar", 1959, "Bengali", ["Drama"]),
    ("Meghe Dhaka Tara", 1960, "Bengali", ["Drama"]),
    ("Charulata", 1964, "Bengali", ["Drama", "Romance"]),
    ("Nayak", 1966, "Bengali", ["Drama"]),
    ("Goopy Gyne Bagha Byne", 1969, "Bengali", ["Comedy", "Fantasy", "Musical"]),
    ("Ghare Baire", 1985, "Bengali", ["Drama"]),
    ("Agantuk", 1991, "Bengali", ["Drama"]),
    ("Chokher Bali", 2003, "Bengali", ["Drama", "Romance"]),
    ("Bakita Byaktigato", 2021, "Bengali", ["Drama", "Comedy"]),
    ("Bela Shuru", 2023, "Bengali", ["Drama"]),
    # --------------------------------------------------------------- Punjabi
    ("Mel Karade Rabba", 2010, "Punjabi", ["Comedy", "Romance"]),
    ("Jatt & Juliet", 2012, "Punjabi", ["Comedy", "Romance"]),
    ("Chaar Sahibzaade", 2014, "Punjabi", ["Animation", "War", "Drama"]),
    ("Punjab 1984", 2014, "Punjabi", ["Drama"]),
    ("Sardaar Ji", 2015, "Punjabi", ["Comedy", "Fantasy"]),
    ("Angrej", 2015, "Punjabi", ["Romance", "Drama"]),
    ("Nikka Zaildar", 2016, "Punjabi", ["Comedy", "Drama", "Romance"]),
    ("Qismat", 2018, "Punjabi", ["Romance", "Drama"]),
    ("Shadaa", 2019, "Punjabi", ["Comedy", "Romance"]),
    ("Jatt Nuu Chudail Takri", 2024, "Punjabi", ["Comedy", "Fantasy", "Horror"]),
]

N_SEED_USERS = 60
SEED_FRACTION = 0.5
_RNG = np.random.default_rng(7)
_RATING_CHOICES = np.array([3.0, 4.0, 4.0, 5.0, 5.0])

LANGUAGES = sorted({entry[2] for entry in INDIAN_MOVIES})


def apply_indian_augmentation(
    movies: pd.DataFrame,
    ratings: pd.DataFrame,
    processed_dir: Path | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Append the Indian catalog + seeded ratings (idempotent).

    Returns updated ``(movies, ratings)`` and, when ``processed_dir`` is given,
    persists the augmented frames back to the parquet cache.
    """
    movies = movies.copy()
    ratings = ratings.copy()

    if "origin" in movies.columns and bool((movies["origin"] == "indian").any()):
        return movies, ratings

    # Tag the existing catalog (MovieLens titles stay language-agnostic).
    movies["origin"] = "movielens"
    movies["language"] = ""

    next_id = int(movies["movie_id"].max()) + 1
    rows = []
    for i, (title, year, language, genres) in enumerate(INDIAN_MOVIES):
        rows.append(
            {
                "movie_id": next_id + i,
                "title": f"{title} ({year})",
                "clean_title": title,
                "year": year,
                "genres": genres,
                "language": language,
                "origin": "indian",
            }
        )
    indian = pd.DataFrame(rows)
    movies = pd.concat([movies, indian], ignore_index=True)

    # Seed ratings from synthetic "critic" users so popularity + item-CF can score Indian titles.
    start_user = int(ratings["user_id"].max()) + 1
    seed_users = list(range(start_user, start_user + N_SEED_USERS))
    indian_ids = indian["movie_id"].tolist()
    seed_rows = []
    for uid in seed_users:
        sampled = pd.Series(indian_ids).sample(
            frac=SEED_FRACTION, random_state=uid
        ).tolist()
        for mid in sampled:
            seed_rows.append(
                (uid, mid, float(_RNG.choice(_RATING_CHOICES)), 0)
            )
    seed_ratings = pd.DataFrame(seed_rows, columns=["user_id", "movie_id", "rating", "timestamp"])
    ratings = pd.concat([ratings, seed_ratings], ignore_index=True)

    if processed_dir is not None:
        processed_dir.mkdir(parents=True, exist_ok=True)
        movies.to_parquet(processed_dir / "movies.parquet")
        ratings.to_parquet(processed_dir / "ratings.parquet")

    print(
        f"Indian cinema augmentation: added {len(indian):,} movies across "
        f"{len(LANGUAGES)} languages + {len(seed_ratings):,} seeded ratings."
    )
    return movies, ratings
